- .pre-commit-config.yaml
- pyproject.toml
- requirements.txt
- src/ansible_creator/utils.py
> Dropping down to Py 3.9

- src/ansible_creator/resources/new_collection/CODE_OF_CONDUCT.md
- src/ansible_creator/resources/new_collection/CONTRIBUTING
- Syncing with ansible-community/collection_template
> Adds more files to initial skeleton

- .github/workflows/tox.yml
Related: https://github.com/ansible/team-devtools/issues/169
> Review codecov config

- codecov.yml
Related: https://github.com/ansible/team-devtools/issues/169
> More codecov fixes

- docs/installing.md
Jira - https://issues.redhat.com/browse/AAP-19818
> Suggest adt installation

- .github/workflows/release.yml
- .github/workflows/tox.yml
- src/ansible_creator/__main__.py
Committed via https://github.com/asottile/all-repos
> Use python3 executable

- docs/installing.md
- tests/units/test_init.py
Related: https://github.com/ansible/ansible-creator/pull/118
> Add a test and update documentation regarding `--init-path` updates

- docs/installing.md
> Update documentation for ansible-project scaffolding

- .prettierignore
- src/ansible_creator/resources/new_collection/.github/workflows/tests.yml.j2
- src/ansible_creator/resources/new_collection/.pre-commit-config.yaml.j2
- tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
- tests/fixtures/collection/testorg/testcol/.pre-commit-config.yaml
Fixes: https://github.com/ansible/ansible-creator/issues/130
> Adds `build-import` job in GHA workflows and includes `flake8` hook in pre-commit-config for collection scaffolding

- docs/installing.md
- src/ansible_creator/resources/ansible_project/README.md.j2
- tests/fixtures/project/ansible_project/README.md
> Update docs and README to the latest directory structure

- src/ansible_creator/constants.py
- tests/fixtures/collection/testorg/testcol/devfile.yaml
- tests/fixtures/project/ansible_project/devfile.yaml
> Update devfile image

- src/ansible_creator/resources/ansible_project/ansible.cfg.j2
- tests/fixtures/project/ansible_project/ansible.cfg
> Fix collection path in ansible.cfg

- src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
- tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
- tests/fixtures/project/ansible_project/.devcontainer/podman/devcontainer.json
Related: https://github.com/ansible/community-ansible-dev-tools-image/pull/38
> Update podman devcontainer file

- .pre-commit-config.yaml
> Unquote versions in precommit

- .pre-commit-config.yaml
Mypy and pylint had some deps carried over from another project, removed.
> Remove extra deps

- pyproject.toml
- src/ansible_creator/config.py
- src/ansible_creator/output.py
- src/ansible_creator/utils.py
- tests/integration/test_init.py
- tests/units/test_init.py
> chore: Update pyproject.toml

- pyproject.toml
- tests/units/test_init.py
This will help clean up tests since ruff can't detect it
> Add known first party

- pyproject.toml
- src/ansible_creator/__main__.py
- src/ansible_creator/compat.py
- src/ansible_creator/constants.py
- src/ansible_creator/types.py
- tests/defaults.py
- tests/units/test_compat.py
- tests/units/test_templar.py
- tests/units/test_utils.py
Was missing in a few files, ruff will make sure it doesn't happen again.
> Add future annotations

- src/ansible_creator/resources/common/devfile/devfile.yaml.j2
- src/ansible_creator/subcommands/init.py
- src/ansible_creator/types.py
- tests/defaults.py
- tests/fixtures/collection/testorg/testcol/devfile.yaml
- tests/fixtures/project/playbook_project/devfile.yaml
- tests/units/test_init.py
Closes: https://github.com/ansible/ansible-creator/issues/255
JIRA issue: https://issues.redhat.com/browse/AAP-26905
> Use project specific name in devfile

- src/ansible_creator/subcommands/init.py
- tests/integration/test_init.py
- tests/units/test_basic.py
- tests/units/test_init.py
They do almost entirely the same thing now. Merging them may not be
desirable for future functionality, but at present there is no reason to
split them.
> Unify scaffolding code

- src/ansible_creator/resources/collection_project/README.md.j2
- src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
- tests/fixtures/collection/testorg/testcol/README.md
- tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Closes: https://github.com/ansible/ansible-creator/issues/262
> Correct the bullhorn link

- docs/installing.md
Related to: https://github.com/ansible/ansible-creator/issues/308
> Update upstream docs to reflect CLI changes

- src/ansible_creator/resources/collection_project/README.md.j2
- src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
- tests/fixtures/collection/testorg/testcol/README.md
- tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Related to: https://github.com/ansible/ansible-creator/issues/261
> Update Invalid Link in README -> Release Notes

- .vscode/settings.json
- src/ansible_creator/resources/playbook_project/inventory/group_vars/db_servers.yml.j2
- src/ansible_creator/resources/playbook_project/inventory/group_vars/production.yml.j2
- src/ansible_creator/resources/playbook_project/inventory/group_vars/test.yml.j2
- src/ansible_creator/resources/playbook_project/inventory/hosts.yml.j2
- tests/fixtures/project/playbook_project/inventory/group_vars/db_servers.yml
- tests/fixtures/project/playbook_project/inventory/group_vars/production.yml
- tests/fixtures/project/playbook_project/inventory/group_vars/test.yml
- tests/fixtures/project/playbook_project/inventory/hosts.yml
> Add test and production inventory group to the playbook project

- src/ansible_creator/arg_parser.py
- src/ansible_creator/resources/collection_project/plugins/filter/hello_world.py.j2
- src/ansible_creator/subcommands/add.py
- tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
- tests/units/test_add.py
JIRA: https://issues.redhat.com/browse/AAP-35644
> Scaffold filter plugin through add subcommand

- src/ansible_creator/resources/common/gitignore/.gitignore.j2
- tests/fixtures/collection/testorg/testcol/.gitignore
- tests/fixtures/project/playbook_project/.gitignore
- tests/units/test_init.py
- Adds .DS_Store which is created by MacOS
- Adds .ansible which is ansible temp directory
> Improve default .gitignore

- .config/dictionary.txt
- src/ansible_creator/constants.py
- tests/fixtures/collection/testorg/testcol/devfile.yaml
- tests/fixtures/common/devfile/devfile.yaml
- tests/fixtures/project/playbook_project/devfile.yaml
JIRA: https://issues.redhat.com/browse/AAP-41915
> Ensure ansible-creator references current devspaces container

- .pre-commit-config.yaml
- .prettierrc.yaml
- CHANGELOG.md
- README.md
- docs/content_creation.md
- docs/contributing.md
- docs/index.md
- docs/installing.md
- src/ansible_creator/resources/collection_project/CODE_OF_CONDUCT.md
- src/ansible_creator/resources/collection_project/README.md.j2
- src/ansible_creator/resources/execution_env_project/README.md
- src/ansible_creator/resources/playbook_project/README.md.j2
- src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/README.md.j2
- tests/fixtures/collection/testorg/testcol/CODE_OF_CONDUCT.md
- tests/fixtures/collection/testorg/testcol/README.md
- tests/fixtures/project/ee_project/README.md
- tests/fixtures/project/playbook_project/README.md
- tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/README.md
Partial: #393
Related: AAP-43305
> Enable prettier and wrap markdown files

- README.md
- src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
- tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
- tests/fixtures/project/playbook_project/.devcontainer/podman/devcontainer.json
Update the devcontainer to match the one used in testing the devtools container during the release process.
> Fix podman devcontainer

- src/ansible_creator/resources/collection_project/.github/workflows/tests.yml.j2
- src/ansible_creator/resources/playbook_project/.github/workflows/tests.yml.j2
- tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
- tests/fixtures/project/playbook_project/.github/workflows/tests.yml
This PR comments out scheduled cron job in collection, playbook project's workflow file and suggests enabling it when required.
> Comment out scheduled cron job in github action workflow file

- src/ansible_creator/resources/collection_project/.github/workflows/tests.yml.j2
- src/ansible_creator/resources/playbook_project/.github/workflows/tests.yml.j2
- tests/fixtures/collection/testorg/testcol/.github/workflows/tests.yml
- tests/fixtures/project/playbook_project/.github/workflows/tests.yml
Follow up PR to address some review comments from https://github.com/ansible/ansible-creator/pull/402
> Update the TO-DO description in tests.yml fixture

- README.md
- src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/galaxy.yml.j2
- src/ansible_creator/resources/playbook_project/collections/ansible_collections/project_org/project_repo/meta/runtime.yml
- tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/galaxy.yml
- tests/fixtures/project/playbook_project/collections/ansible_collections/weather/demo/meta/runtime.yml
Fixes #439 
Add collection metadata files to ensure the collection is recognizable as a collection and passes ansible-lint.
```
$ ansible-creator init collection foo.bar /tmp/ctest
Note: collection project created at /tmp/ctest
$ ansible-creator add resource role trole /tmp/ctest
Note: Resource added to /tmp/ctest
$ tree /tmp/ctest
/tmp/ctest
├── CHANGELOG.rst
├── changelogs
│   └── config.yaml
├── CODE_OF_CONDUCT.md
├── CONTRIBUTING
├── devfile.yaml
├── docs
│   └── docsite
│       └── links.yml
├── extensions
│   ├── eda
│   │   └── rulebooks
│   │       └── rulebook.yml
│   └── molecule
│       ├── integration_hello_world
│       │   └── molecule.yml
│       └── utils
│           ├── playbooks
│           │   ├── converge.yml
│           │   └── noop.yml
│           └── vars
│ …
```
> Fix playbook galaxy

- .ansible-lint.yml
- .claude/settings.local.json
- .github/workflows/release.yml
- .pre-commit-config.yaml
- AGENTS.md
- src/ansible_creator/resources/common/gitignore/__meta__.yml
> fix: ensure ansible-lint is passing

- codecov.yml
- pyproject.toml
- src/ansible_creator/__main__.py
- src/ansible_creator/arg_parser.py
- src/ansible_creator/compat.py
- src/ansible_creator/subcommands/add.py
- src/ansible_creator/subcommands/init.py
- src/ansible_creator/utils.py
Unblocks: #477
Related: AAP-54472
> fix: ignore .DS_Store files
