ansible/ansible-creator

- .github/release-drafter.yml
- .github/workflows/ack.yml
- .pre-commit-config.yaml
- updated renamed repos
- removed no-commit-to-branch because it does not work with push
triggered jobs, and these are needed for codecov.
> More github workflow updates

- .config/constraints.txt
- src/ansible_creator/subcommands/init.py
- tests/conftest.py
- tests/integration/test_init.py
- tests/units/test_init.py
--init-path should only create namespace / collection sub directories if init-path ends with collections/ansible_collections
also bumps mkdocs-material to 9.15.7 due to https://github.com/squidfunk/mkdocs-material/blob/master/CHANGELOG#L22
> update init-path behaviour

- src/ansible_creator/resources/new_collection/.github/workflows/release.yml.j2
- tests/fixtures/collection/testorg/testcol/.github/workflows/release.yml
Adds the correct workflow secret key for [release_galaxy.yaml](https://github.com/ansible/ansible-content-actions/blob/c2cf076d7518d7dfd46ad90ade5428d651a68f83/.github/workflows/release_galaxy.yaml#L15C7-L15C29); fixing the `release.yaml` workflow script that is generated using `ansible-creator init`.
The [ansible-content-actions](https://github.com/ansible/ansible-content-actions/tree/main/.github/workflows) has two release workflows for automation hub and galaxy. Each uses different secret [key values](https://github.com/ansible/ansible-content-actions/blob/c2cf076d7518d7dfd46ad90ade5428d651a68f83/.github/workflows/release.yaml#L18), `ah_token` and `ansible_galaxy_api_key`.
> fix: replace automation hub workflow secret with release_galaxy secret

- src/ansible_creator/cli.py
- src/ansible_creator/config.py
- src/ansible_creator/output.py
- tests/units/test_basic.py
- tests/units/test_init.py
- We were redundantly passing output related args to Config class. 
- We should instead be passing the output class object (cc @shatakshiiii)
> do not send output args to config class

- src/ansible_creator/cli.py
- src/ansible_creator/subcommands/init.py
- tests/integration/test_init.py
- tests/units/test_init.py
With v24.4.0, creator erroneously raises an error even if the final `init-path` exists but is empty. It should only complain when the `init-path` is non-empty and `--force` is disabled.
> Do not fail if `init-path` exists but is empty

- src/ansible_creator/resources/ansible_project/ansible.cfg.j2
- tests/fixtures/project/ansible_project/ansible.cfg
After reconsideration of #159, remove the collection path completely
- The playbook adajacent collection will be found automatically
- The use of collection path is incompatible with ADE as it removes the venv site packages directory from the collection search path
> Remove the collection path

- src/ansible_creator/constants.py
- src/ansible_creator/utils.py
Related #164 
When ansible-creator is installed by pip, some pycache and pyc files are created in the collection unit test directory:
```
(venv) m910x ➜  test tree venv/lib/python3.12/site-packages/ansible_creator/resources/new_collection/tests/unit/                                   
venv/lib/python3.12/site-packages/ansible_creator/resources/new_collection/tests/unit/
├── __pycache__
│   └── test_basic.cpython-312.pyc
└── test_basic.py
```
These cause a traceback when scaffolding:
```
test ansible-creator init --project collection collection=a.b --init-path /tmp/foo --force      
Warning: re-initializing existing directory /tmp/foo
Traceback (most recent call last):
File "/tmp/test/venv/bin/ansible-creator", line 8, in <module>
sys.exit(main())
^^^^^^
File …
```
> Don't scaffold pycache or pyc

- .pre-commit-config.yaml
- pyproject.toml
- src/ansible_creator/cli.py
- src/ansible_creator/output.py
- src/ansible_creator/subcommands/init.py
- src/ansible_creator/utils.py
- tests/units/test_basic.py
- tests/units/test_init.py
- tests/units/test_utils.py
- Switch to pathlib Paths when possible
- Remove exccluded PTH ruff errors
- Exclude _version.py since it's generated
- Changes types as needed
- Move the expand path test into a new test_utils file
> Remediate ruff errors related to not using `pathlib.Path`

- .pre-commit-config.yaml
For deps, the stage is manual so the ci skip is uneeded
Sorted as needed
> Update precommit config

- src/ansible_creator/config.py
- src/ansible_creator/constants.py
- tests/units/test_init.py
FIxes: #230
Adds checks for collection name requirements and new tests for the new checks. 
Examples:
Command: `ansible-creator init COLLECTION.NAME`
Error output: `Error: Collection name can only contain lower case letters, underscores, and numbers and cannot begin with an underscore.`
Command: `ansible-creator init na.co`
Error output:  `Error: Collection namespace and name must be longer than 2 characters.`
> Adding collection name requirement checks 

- pyproject.toml
- src/ansible_creator/resources/ansible_project/collections/requirements.yml.j2
- src/ansible_creator/resources/new_collection/README.md.j2
- src/ansible_creator/resources/new_collection/extensions/molecule/utils/vars/vars.yml
- src/ansible_creator/resources/new_collection/meta/runtime.yml
- src/ansible_creator/resources/new_collection/plugins/filter/hello_world.py.j2
- src/ansible_creator/resources/new_collection/tests/unit/__init__.py
- tests/fixtures/collection/testorg/testcol/README.md
- tests/fixtures/collection/testorg/testcol/extensions/molecule/utils/vars/vars.yml
- tests/fixtures/collection/testorg/testcol/meta/runtime.yml
- tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
- tests/fixtures/collection/testorg/testcol/tests/unit/__init__.py
- tests/fixtures/project/ansible_project/collections/requirements.yml
Currently, both the scaffolded content types fail GHA workflow checks and pre-commit hooks. This patch fixes that.
> Assorted CI fixes for scaffolded content

- .pre-commit-config.yaml
- src/ansible_creator/compat.py
- src/ansible_creator/config.py
- src/ansible_creator/output.py
- src/ansible_creator/utils.py
- tests/units/test_init.py
Restore pylint version to match other repositories.
This is a valid deprecation message, so we'll disable reporting via pylint until we drop 3.10.
Also added some class doc strings to pass latest version of pydoclint
> chore: Update .pre-commit-config.yaml

- src/ansible_creator/constants.py
- src/ansible_creator/resources/ansible_project/.vscode/extensions.json
- src/ansible_creator/resources/common/devcontainer/.devcontainer/devcontainer.json.j2
- src/ansible_creator/resources/common/devcontainer/.devcontainer/docker/devcontainer.json.j2
- src/ansible_creator/resources/common/devcontainer/.devcontainer/podman/devcontainer.json.j2
- src/ansible_creator/resources/common/devfile/devfile.yaml.j2
- src/ansible_creator/resources/common/vscode/.vscode/extensions.json.j2
- src/ansible_creator/resources/new_collection/.vscode/extensions.json
- src/ansible_creator/subcommands/init.py
- src/ansible_creator/templar.py
- src/ansible_creator/types.py
- src/ansible_creator/utils.py
- tests/fixtures/collection/testorg/testcol/.devcontainer/devcontainer.json
- tests/fixtures/collection/testorg/testcol/.devcontainer/docker/devcontainer.json
- tests/fixtures/collection/testorg/testcol/.devcontainer/podman/devcontainer.json
- tests/fixtures/collection/testorg/testcol/.vscode/extensions.json
- tests/fixtures/project/ansible_project/.devcontainer/devcontainer.json
- tests/fixtures/project/ansible_project/.devcontainer/docker/devcontainer.json
- tests/fixtures/project/ansible_project/.devcontainer/podman/devcontainer.json
- tests/fixtures/project/ansible_project/.vscode/extensions.json
- tests/units/test_templar.py
- tests/units/test_utils.py
- Update the extension list to include RH auth
- Set the recommended extensions as shared constant
- Promote the vscode files to a common resource
- Share a list of common resources between project types
- Move the list of recommended extensions to a constant
- template data is now a dataclass to better track the vars needed for templating, convert to dict at the last minute when handing off to jinja
- Add a new `json` filter for jinja
- Add some tests for the `json` jinja filter
> Add RH auth extension recommendation

- tests/conftest.py
- tests/units/test_basic.py
This change uses pathlib in the test conf instead of hardcoding it to the home directory for the ansible user. Related to https://github.com/ansible/ansible-creator/pull/250
> avoid hardcoded path in test conf

- src/ansible_creator/output.py
- src/ansible_creator/resources/new_collection/tests/unit/test_basic.py.j2
- tests/fixtures/collection/testorg/testcol/tests/unit/test_basic.py
- tests/units/test_output.py
This _should_ bring code coverage to 100% and eliminate any issues in the scan.
- Remove unecessary class type hint
- Modify the scaffolded collection unit test to not test a constant
- Add a couple test which should bring code coverage to 100% :)
> Additional tests, minor fixes

- README.md
- docs/contributing.md
- mkdocs.yml
As a part of the [Consolidating Ansible discussion platforms initiative](https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812), this PR adds the communication section template defined by the community to the README and the docsite. Similar PRs are now being raised across all the Ansible ecosystem projects.
Thanks!
> Add communication details

- src/ansible_creator/subcommands/init.py
- src/ansible_creator/utils.py
- tests/units/test_utils.py
Walker recursively looks for paths that need to be copied over, and returns a list of destination/original path objects
Copier takes that list and does the actual copying.
Notes:
* ~~meta handling is broken right now, I forgot about it~~
* ~~tests have not been touched yet~~
* ~~`--force` is currently a no-op~~
* ~~.gitignore's meta is not getting applied correctly~~
* With `--force` reinstated, there is no good way to access the file conflict handling of Copier
* Tests have been added
Open Questions:
* Should Walker know to skip existing files that have no changes?
* Answer: yes
Related issue: https://github.com/ansible/ansible-creator/issues/163
> Split Copier into Walker and Copier steps

- src/ansible_creator/config.py
- tests/units/test_basic.py
This PR adds a small check in config to set project type as "playbook" from "ansible-project". This is required when args are directly passed to config class (without any interaction with arg_parser)
For example: https://github.com/ansible/ansible-dev-tools/blob/main/src/ansible_dev_tools/resources/server/creator.py#L138-L147
Related PR: https://github.com/ansible/ansible-dev-tools/pull/430
> Add a check in config to set project type as playbook

- pyproject.toml
Related: https://github.com/ansible/team-devtools/issues/229
> Add support for py313

- docs/installing.md
Related Issue : https://github.com/ansible/ansible-creator/pull/305, https://github.com/ansible/ansible-creator/issues/308
This PR adds detailed documentation for the `add` subcommand in the `installing.md` file, covering the following:
- **Positional Arguments:** Added descriptions for `content-type` (options: `resource`, `plugin`) and `resource-type` (options: `devfile`, `devcontainer`, `role`).
- **Usage Examples:** Provided command examples for `ansible-creator add resource devfile` and similar commands.
This update mentions the `add` subcommand documentation for better usability and clarity.
> Update upstream doc with add subcommand details in installing.md

- .pre-commit-config.yaml
- pyproject.toml
- src/ansible_creator/arg_parser.py
- src/ansible_creator/cli.py
- src/ansible_creator/config.py
- src/ansible_creator/exceptions.py
- src/ansible_creator/output.py
- src/ansible_creator/resources/collection_project/plugins/filter/hello_world.py.j2
- src/ansible_creator/subcommands/add.py
- src/ansible_creator/subcommands/init.py
- src/ansible_creator/templar.py
- src/ansible_creator/utils.py
- tests/fixtures/collection/testorg/testcol/plugins/filter/hello_world.py
- tests/units/test_init.py
> Remove type for self

- docs/installing.md
> Clean up for  upstream docs for add subcommand and devfile resource type

- .config/dictionary.txt
- src/ansible_creator/arg_parser.py
- src/ansible_creator/config.py
- src/ansible_creator/constants.py
- src/ansible_creator/resources/common/execution-environment/execution-environment.yml.j2
- src/ansible_creator/subcommands/add.py
- src/ansible_creator/types.py
- tests/fixtures/common/execution-environment/execution-environment.yml
- tests/units/test_add.py
Related JIRA: https://issues.redhat.com/browse/AAP-36883
> Add support to scaffold execution environment sample file

- src/ansible_creator/resources/collection_project/plugins/lookup/hello_world.py.j2
- tests/fixtures/collection/testorg/testcol/plugins/lookup/hello_world.py
Fixes the smoke test failures on the tox-ansible repo CI
> Changes to the lookup template to encounter tox-ansible sanity check failures

- src/ansible_creator/resources/collection_project/galaxy.yml.j2
- tests/fixtures/collection/testorg/testcol/galaxy.yml
Related PR: https://github.com/ansible/ansible-creator/pull/348
This change is required to fix `ModuleNotFoundError: No module named 'ansible_collections.ansible.utils'` when running tox-ansible sanity check on a scaffolded collection containing action plugins.
Example of tox-ansible sanity check: `python3 -m tox --ansible -e sanity-py3.13-2.18 --conf tox-ansible.ini`
> Update scaffolded galaxy file in a collection: Add ansible.utils as a dependency

- src/ansible_creator/arg_parser.py
- src/ansible_creator/resources/collection_project/plugins/action/hello_world.py.j2
- src/ansible_creator/resources/collection_project/plugins/modules/hello_world.py.j2
- src/ansible_creator/subcommands/add.py
- src/ansible_creator/utils.py
- tests/fixtures/collection/testorg/testcol/plugins/action/hello_world.py
- tests/fixtures/collection/testorg/testcol/plugins/modules/hello_world.py
- tests/units/test_add.py
- This PR adds support to scaffold  `action` plugins in an existing ansible collection using add subcommand.
- Additionally scaffolds a module file with plugin `DOCUMENTATION` and `EXAMPLES` for corresponding action plugin.
- Also, it creates a sample `hello_world.py` action plugin template when initializing a collection project using init subcommand.
**CLI usage:** 
```
ansible-creator add plugin action your_plugin_name /path/to/your/existing/ansible_collection
```
**Related JIRA**: https://issues.redhat.com/browse/AAP-36202
> Scaffold action plugin through add subcommand

- .vscode/launch.json
- docs/installing.md
- src/ansible_creator/arg_parser.py
- src/ansible_creator/resources/collection_project/plugins/module/hello_world.py.j2
- src/ansible_creator/resources/collection_project/plugins/sample_module/hello_world.py.j2
- src/ansible_creator/subcommands/add.py
- tests/fixtures/collection/testorg/testcol/plugins/sample_module/hello_world.py
- tests/units/test_add.py
**SUMMARY**
This PR adds support to scaffold module plugins in an existing ansible collection using add subcommand.
A new "module" subdirectory has been created under the plugins directory.
**CLI usage:**
`ansible-creator add plugin module your_module_name /path/to/your/existing/ansible_collection
`
Related JIRA: https://issues.redhat.com/browse/AAP-36203
> Scaffold a generic module plugin in an existing ansible collection using add subcommand.

- docs/installing.md
- src/ansible_creator/resources/collection_project/plugins/test/sample_test.py.j2
- tests/fixtures/collection/testorg/testcol/plugins/test/sample_test.py
- tests/units/test_init.py
Updated the docs and fixed an issue where sample_test.py had a function  named _hello_world(args..). Renamed it to _sample_test(args..)
> Updated the Installing.md docs and updated the sample_test.py.j2 file

- .env
- .gitignore
- mise.toml
Due to https://github.com/dependabot/dependabot-core/issues/1455
we are forced to add a `.python-version` file so dependabot will not use unsupported older python when running.
Still, we need to reconfigure `mise` to tell it to ignore this file.
Related: https://github.com/ansible/ansible-compat/pull/479
Related: AAP-43336
> Workaround for dependabot improper python version

- .config/pydoclint-baseline.txt
- tests/units/test_add.py
This PR refactors `test_add.py` file to address the following objectives:
- Group related test scenarios: Use `pytest.mark.parametrize` to reuse shared logic and reduce boilerplate code.
- Remove Pylint Suppression: Eliminate the need for suppressing the C0302 (too-many-lines) warning.
JIRA: [AAP-44157](https://issues.redhat.com/browse/AAP-44157)
Closes: https://github.com/ansible/ansible-creator/issues/398
> Refactor plugin tests in test_add.py

- docs/installing.md
- src/ansible_creator/resources/collection_project/plugins/modules/sample_module.py.j2
- src/ansible_creator/resources/collection_project/plugins/test/sample_test.py.j2
- src/ansible_creator/resources/collection_project/tests/integration/targets/hello_world/tasks/main.yml.j2
- tests/fixtures/collection/testorg/testcol/plugins/modules/sample_module.py
- tests/fixtures/collection/testorg/testcol/plugins/test/sample_test.py
- tests/fixtures/collection/testorg/testcol/tests/integration/targets/hello_world/tasks/main.yml
See https://github.com/ansible/tox-ansible/actions/runs/14998128541/job/42137739053?pr=436
tox-ansible uses the output of ansible-creator to test sanity and integration runs. Unfortunately, as of 25.3.0, the generated content does not pass sanity or integration checks. This is an attempt to bring those scaffolded files into compliance.
The added license in sample_module is to allow `validate-module`'s `missing-gplv3-license` check to pass. _Arguably_, this test should be added to a global ignores, but as the license is added to other plugins automatically, I deemed it out of scope to fix properly.
> Update scaffolded modules to avoid sanity errors

- .vscode/settings.json
This PR adds a file association in settings.json to treat all `*.j2` files as YAML. This enables YAML syntax highlighting and language features for Jinja2 template files, making it easier to work with Ansible files and templates that use the .j2 extension.
Fixes: https://github.com/ansible/ansible-creator/issues/221
> Enable yaml syntax highlighting for jinja2 templated files

- src/ansible_creator/resources/common/patterns/sample_pattern/meta/pattern.json.j2
- src/ansible_creator/subcommands/add.py
- This PR dynamically set the pattern name based on the CLI input.
- [This](https://github.com/ansible/ansible-creator/blob/main/src/ansible_creator/resources/common/patterns/sample_pattern/meta/pattern.json#L3) name field needs to be set as actual pattern name received from CLI and the one used in pattern directory name.
> Enable templating for pattern name in pattern.json file
